/**
 * 数据库操作演示
 * 这里列举了常见数据库操作方法，方便大家学习。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChildrenInputDto } from './childrenInputDto';
import { PostInputDto } from './postInputDto';

export interface PersonInputDto { 
    /**
     * Id
     */
    id?: number;
    /**
     * 姓名
     */
    name: string;
    /**
     * 年龄
     */
    age: number;
    /**
     * 住址
     */
    address?: string;
    /**
     * 电话号码
     */
    phoneNumber?: string;
    /**
     * QQ 号码
     */
    qq?: string;
    /**
     * 孩子
     */
    childrens?: Array<ChildrenInputDto>;
    /**
     * 孩子
     */
    posts?: Array<PostInputDto>;
}