/**
 * 数据库操作演示
 * 这里列举了常见数据库操作方法，方便大家学习。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: monksoul@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PostInputDto { 
    /**
     * 主键
     */
    id?: number;
    /**
     * 名称
     */
    name?: string;
}