// <auto-generated />
using System;
using Fur.EntityFramework.Core.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fur.EntityFramework.Core.Migrations.FurMultipleSqlServerDb
{
    [DbContext(typeof(FurMultipleSqlServerDbContext))]
    [Migration("20200727063403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("Fur.DatabaseAccessor.MultipleTenants.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2020, 7, 27, 14, 34, 2, 947, DateTimeKind.Local).AddTicks(8901),
                            Host = "localhost:44307",
                            IsDeleted = false,
                            Name = "默认租户",
                            UpdatedTime = new DateTime(2020, 7, 27, 14, 34, 2, 948, DateTimeKind.Local).AddTicks(8459)
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2020, 7, 27, 14, 34, 2, 949, DateTimeKind.Local).AddTicks(255),
                            Host = "localhost:41529",
                            IsDeleted = false,
                            Name = "默认租户",
                            UpdatedTime = new DateTime(2020, 7, 27, 14, 34, 2, 949, DateTimeKind.Local).AddTicks(261)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
